services:
    - name: mysqlbroker
      id: "3101b971-1044-4816-a7ac-9ded2e028079"
      description: "MySQL service for application development and testing"
      tags:
        - mysql
        - relational
      max_db_per_node: 250
      metadata: "mett"
      bindable: true
      provider: "inspur"
      listing:
         imageUrl: ~
         blurb: "MySQL service for application development and testing"
      plans:
          - name: 5mb
            id: "2451fa22-df16-4c10-ba6e-1f682d3dcdc9"
            description: "Shared MySQL Server"